version: 2

build:
  os: ubuntu-24.04
  apt_packages:
    - cmake
    - g++
    - libeigen3-dev
    - libfmt-dev
    - mold
    - ninja-build
  tools:
    python: "3.13"
  jobs:
    post_install:
      - ./scripts/build-and-deploy.sh

sphinx:
  configuration: docs/conf.py
  fail_on_warning: true

python:
  install:
    - requirements: python/requirements.txt
    - requirements: docs/requirements.txt
